# Generated by Django 2.1.5 on 2019-07-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzas',
            name='urlImg',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
