# Generated by Django 2.1.5 on 2019-07-10 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Medidas', '0001_initial'),
        ('Usuarios', '0001_initial'),
        ('Pizzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Medidas.Medidas')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizzas.Pizzas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios')),
            ],
            options={
                'db_table': 'CARRITO',
            },
        ),
    ]
