# Generated by Django 2.1.5 on 2019-07-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=80, unique=True)),
                ('telefono', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'USUARIOS',
            },
        ),
    ]
